packages/backend/constants/index.ts
packages/backend/prisma/migrations/20230626152627_add_scope_to_account/migration.sql
packages/backend/prisma/migrations/20230627062354_drop_scope_from_accounts/migration.sql
packages/backend/prisma/migrations/20230628045235_use_client_custom_app_creds/migration.sql
packages/backend/prisma/migrations/20230628061559_create_app_table/migration.sql
packages/backend/prisma/migrations/20230628150321_link_app_connection/migration.sql
packages/backend/prisma/migrations/20230629051826_/migration.sql
packages/backend/prisma/schema.prisma
packages/backend/prisma/seed.ts
packages/backend/routes/v1/crm/auth.ts
packages/backend/routes/v1/metadata.ts
packages/backend/services/auth.ts
packages/backend/services/connection.ts
packages/js/src/index.ts
packages/js/vite.config.js
packages/react/src/lib/revert-dev.js

feat: oauth flow via customer apps

---

packages/backend/routes/index.ts
packages/backend/services/auth.ts
packages/client/package.json
packages/client/src/data/axios/index.ts
packages/client/src/data/hooks/index.ts
packages/client/src/data/localstorage/index.ts
packages/client/src/home/editCredentials.tsx
packages/client/src/home/integrations.tsx
yarn.lock

**Demo**: https://www.loom.com/share/935a0baf08634608baf8cd1e04f068b0?sid=2321bf91-ad5a-4e97-9c08-79485d0e366e

Update credentials ui

---

packages/backend/routes/v1/connection/index.ts
packages/backend/services/connection.ts

Adds a `getWebhook` endpoint that allows you to check if a connection already has a webhook endpoint created for it. It gives an error if we search for a connection webhook that is not created. 
-   [x] Tested locally for connection webhooks that exist
-   [x] Tested locally for connection webhooks that don't exist

feat: add get webhook endpoint

---

packages/backend/index.ts

Skip certain routes on the rate limiter. 
Tested locally

fix: add allowlist on rate limiter

---

.github/workflows/deploy-fern-docs.yml
package.json
yarn.lock

The version of the `fern-api` package in `package.json` always need to line up with the version in `fern.config.json`. If they don't align you will see non-deterministic errors.

:herb: fix fern generate 

---

CONTRIBUTING.md
README.md

Add contributing.md and update README. 

chore(repo): add contributing.md

---

.env.example
README.md

update docker compose instructions

chore(repo): update docker compose instructions

---

packages/backend/services/auth.ts

Create apps only when not present for an account. So far, the code was trying to create multiple entries for apps even when the apps are present for an account when a new user signs up. 

fix: create apps only when not present

---

packages/react/README.md
packages/vue/README.md

chore(docs): update sdk readme

---

packages/js/package.json
packages/react/.env.example
packages/react/package.json
packages/react/src/lib/useRevertConnect.ts
packages/react/vite.config.ts
packages/vue/.env.example
packages/vue/package.json
packages/vue/src/lib/useRevertConnect.ts
packages/vue/vite.config.ts

ensure react/next/vue sdks get the right cdn path from environments whilst ensuring a smooth DX locally. This was rendering our users not able to fetch the integration metadata from the frontend. 

fix: ensure react/next/vue sdks get the right cdn path from env

---

packages/backend/index.ts

Makes Moesif an option config for running Revert backend. 
-   [x] Tested with and without the `.env` variables

chore(dev-ex): make moesif optional for local dev

---

packages/js/src/index.ts

As described our users 
```
So we open the hubspot auth page in a new tab with this code -
revertConnect?.open?.("hubspot")
It does open it in a new tab but then we also receive the error in the screenshot,
We were making an api call after the above mentioned line and it was not getting called due to this error.
For now we are making the api call before executing the open function from Revert as a temporary solution.
We are currently using
"@revertdotdev/revert-react": "^0.0.15", 
``` 
-   [x] Tested locally and staging

fix: only call `onClose` when passed via props

---

CONTRIBUTING.md
README.md
packages/backend/README.md
packages/backend/package.json
packages/react/.env.example
packages/vue/.env.example

Improves readmes for local setup. 
Partially closes #261 
No tests required

chore(repo): improve backend readme for setup locally

---

.github/workflows/deploy-fern-docs.yml
fern/generators.yml

fix: fix gh workflow for fern docs

---

packages/backend/prisma/seed.ts

According to pipedrive [docs](https://developers.pipedrive.com/docs/api/v1/Persons#getPersons) email is returned in its own array of object.
-   [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)

Corrected pipedrive email target field

---

fern/docs.yml

update docs accent color to an on brand color
Also filed with an issue with Fern: https://github.com/fern-api/fern/issues/2288 

fix: update docs accent color

---

README.md

In this update, I have eliminated redundant command lines in the setup script, specifically the duplicate cp .env.example .env commands. This change simplifies the initial setup process and reduces potential confusion for new contributors.
- [-] Bug fix (non-breaking change which fixes an issue)
before:
```shell
git clone --depth 1 https://github.com/revertinc/revert
cp .env.example .env
cp .env.example .env
cp packages/backend/.env.example packages/backend/.env
cp packages/client/.env.example packages/client/.env
cp packages/js/.env.example packages/js/.env
cp packages/react/.env.example packages/react/.env
cp packages/vue/.env.example packages/vue/.env
docker-compose run db-seed
docker-compose up -d
```
after:
```shell
git clone --depth 1 https://github.com/revertinc/revert
cp …
```

chore: remove duplicate commands on repo's readme

---

packages/js/package.json

Build directories `packages/react/lib/build/revert-dev.js` and `packages/vue/lib/build/revert-dev.js`  automatic generation.
-   [X] By executing `yarn workspace @revertdotdev/js dev`

fix: Updated win32 script to automatically create build folders

---

packages/backend/prisma/client.ts
packages/backend/prisma/connectionIdMigrate.ts
packages/backend/prisma/migrations/20240129132405_unique_third_party_per_environment_constraint_environments_connection_relation_added/migration.sql
packages/backend/prisma/migrations/20240129175309_unique_third_party_per_tenant_per_environment_constraint_added/migration.sql
packages/backend/prisma/migrations/20240130012345_unique_third_party_per_environment_order_changed/migration.sql
packages/backend/prisma/migrations/20240130012936_unique_third_party_per_tenant_per_environment_added/migration.sql
packages/backend/prisma/migrations/20240130121018_unique_tenant_per_environment_constraint_added/migration.sql
packages/backend/prisma/migrations/20240130121641_/migration.sql
packages/backend/prisma/migrations/20240130130301_/migration.sql
packages/backend/prisma/migrations/20240131115131_1/migration.sql
packages/backend/prisma/schema.prisma
packages/backend/routes/v1/chat/auth.ts
packages/backend/routes/v1/crm/auth.ts
packages/backend/routes/v1/ticket/auth.ts

1. Multiple connections with same `t_id` & `tp_id` can exist provided they belong to different environment
2. Unique Constraints added `uniqueThirdPartyPerTenantPerEnvironment` & `uniqueThirdPartyPerEnvironment`
-   [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [X] Check by establishing connection with same `tp_id` & `t_id` via different environments
-   Navigate to backend package `cd packages/backend`
-   Run `npx ts-node prisma/connectionIdMigrate.ts`
-   [X] I have commented my code, particularly in …

fix: Multiple tenantId and tp_id conflict

---

packages/backend/routes/v1/ticket/auth.ts

Added missing `tp_account_url` field in jira  update query.

fix: missing tp_account_url field in jira update connection

---

fern/definition/common/unified.yml
fern/definition/crm/contact.yml
fern/definition/crm/deal.yml
fern/definition/crm/event.yml
fern/definition/crm/lead.yml
fern/definition/crm/note.yml
fern/definition/crm/task.yml
fern/definition/crm/user.yml

ensure `additional` block is present in docs
Documentation generated in preview mode 

docs: ensure `additional` block is present in docs

---

CONTRIBUTING.md

Fix broken links pointing to `https://github.com/revert/revert` instead of  `https://github.com/revertinc/revert` in CONTRIBUTING.md
I can access the open the desired links instead of a `404` error.

docs: fix broken links in CONTRIBUTING.md

---

packages/js/src/index.ts

Start showing object name in field mapping ui. 
-   [x] Tested locally (screenshot attached)

feat: show object name in field mapping ui

---

packages/backend/services/crm/contact.ts
packages/backend/services/crm/event.ts

- Return Zoho response upon creating a event instead of returning payload (Zoho create event).
- Assign contacts as an empty array if it is an empty string (for zoho SearchContacts)
-   [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)

fix: Return event details upon creation

---

packages/client/src/home/index.tsx
scripts/backend/backup_rds.sh

hotfix: ensure default env is set on integration dashboard
Tested with reproducing the bug where the screen became blank when trying to set OAuth creds for our users. 

fix: ensure default env is set on integration dashboard

---

fern/definition/connection.yml
packages/backend/oas/openapi.yml
packages/backend/routes/v1/crm/authHandlers/hubspot.ts
packages/backend/services/connection.ts
packages/client/src/home/editCredentials.tsx

1. Adds a connection import endpoint that allows users to move into Revert from any other integration provider or from in-house management of OAuth tokens. 
2. We also show the `appId` on the integration dashboard
Tested importing tokens for new connections 

feat: add connection import endpoint

---

packages/backend/services/crm/company.ts
packages/backend/services/crm/contact.ts
packages/backend/services/crm/deal.ts
packages/backend/services/crm/event.ts
packages/backend/services/crm/lead.ts
packages/backend/services/crm/note.ts
packages/backend/services/crm/task.ts

fixes #546 
Adds pagination support for Zoho CRM, Close crm, ms dynamics 365 sales, pipedrive.
Pagination has been added to the endpoints that have search api in the above mentioned crms.
Remaining: Salesforce (a discussion is required on how to proceed towards pagination in this integration). (Edit: pagination will be handled by the users themselves for the salesforce crm).
via postman
-   [x] My changes generate no new …

feat: remaining Support Pagination in CRM search API endpoints

---

fern/definition/internal/account.yml
packages/backend/oas/openapi.yml
packages/backend/routes/index.ts
packages/backend/services/Internal/account.ts
packages/backend/services/app.ts
packages/backend/services/auth.ts
packages/client/src/features/integration/AddIntegration.tsx
packages/client/src/features/integration/CreatedIntegration.tsx
packages/client/src/features/integration/enums/metadata.ts
packages/client/src/home/environmentSelector.tsx
packages/client/src/home/integrations.tsx
packages/client/src/home/navbar.tsx
packages/client/src/layout/MainHeader.tsx

Closes #496 
Closes #496
/claim #496
-   [x] New and existing unit tests pass locally with my changes
https://github.com/revertinc/revert/assets/65061890/a56e9fc6-b1ae-42bf-8345-91d85a8812a1

feat: only create apps that are needed by a developer

---

packages/client/src/features/integration/CreatedIntegration.tsx
packages/client/src/home/integrations.tsx
packages/client/src/layout/MainHeader.tsx

- Relates #496 
https://github.com/revertinc/revert/assets/65061890/b6fba68a-4824-4764-97b6-6f28e75579e8

fix: created apps page to have 3 cols

---

packages/js/src/index.ts
packages/react/src/App.tsx
packages/react/src/lib/useRevertConnect.ts
packages/vue/src/App.vue

- Allow connection only when config values are not null, undefined. 
- On the Initial Renders config props could be null or undefined that wouldn't mean they intend or passed that strict value.
- Handling "Revert is Loaded or not" on open, inOrder to not give console errors on every initial renders if the value is null or undefined.
- In React Example we are disabling the button -> Inorder to check comment out disabled in button.
https://github.com/revertinc/revert/assets/65061890/6945c865-4d2d-4734-b1c2-9d1fad90051e
https://github.com/revertinc/revert/assets/65061890/c4c614b0-f15d-4057-b870-600bf1e7d647
Fixes #564 
- …

fix: connecting to revert on null props

---

packages/js/src/index.ts

- when user is interested in fieldMappings explictly specify closeAfterOAuthFlow: false and if not specified it will assume customers are not interested in fieldMappings regardless of AccountFieldMappingsConfig. 
- Closes #576 
When FieldMapping Config is there:  
- `closeAfterOAuthFlow: true`: customers are not interested in fieldMappings regardless of config.
- `closeAfterOAuthFlow: false`: customers are interested in fieldMappings.
When FiledMapping Config is not there (Attaching Demo of this as it is little tricky): 
- `closeAfterOAuthFlow: true`: customers are not interested in fieldMappings  it will close.
- `closeAfterOAuthFlow: false`: customers are interested in fieldMappings but there is not config so it will show the container to close but won't show the filedMappings. …

fix: handle `closeAfterOAuthFlow` with `fieldMapping` account config

---

packages/backend/services/connection.ts

- Now it won't give `"field": "Required parameter appId was null or undefined when calling v1EndpointCreate."` and will give understandable response object.
- Fixes: issue in sentry - eventId 5bd35d6f
https://github.com/revertinc/revert/assets/65061890/4250abf4-df48-45a3-b0f6-c65e643c429a

fix: Webhook endpoints to handle unauthorized API access

---

fern/definition/crm/company.yml
fern/definition/crm/contact.yml
fern/definition/crm/deal.yml
fern/definition/crm/event.yml
fern/definition/crm/lead.yml
fern/definition/crm/note.yml
fern/definition/crm/task.yml
fern/definition/crm/user.yml
packages/backend/helpers/crm/hubspot.ts
packages/backend/helpers/crm/transform/unify.ts
packages/backend/oas/openapi.yml
packages/backend/services/crm/company.ts
packages/backend/services/crm/contact.ts
packages/backend/services/crm/deal.ts
packages/backend/services/crm/event.ts
packages/backend/services/crm/note.ts
packages/backend/services/crm/task.ts
packages/backend/services/crm/user.ts
packages/react/src/App.tsx

adds support for fetching associated objects in Hubspot crm get apis.
Fixes #540 
[associtaions.webm](https://github.com/user-attachments/assets/b0055feb-18b8-4793-b3bf-45dea38153d2)
via postman
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes
Any dependent changes have been merged and published in downstream modules

feat:  Support for Hubspot associations API 
