revertinc/revert

- packages/backend/helpers/filterLeadsFromContacts.ts
- packages/backend/services/lead.ts
> Implement Pagination for Leads

- packages/backend/services/company.ts
- packages/backend/services/contact.ts
- packages/backend/services/deal.ts
- packages/backend/services/event.ts
- packages/backend/services/note.ts
- packages/backend/services/task.ts
> feat: add pagination for other apis

- packages/backend/services/proxy.ts
Fixed the error due to wrong media type
> fix: allow proxy post calls on hubspot

- packages/backend/constants/index.ts
- packages/backend/package.json
- packages/backend/prisma/migrations/20230626152627_add_scope_to_account/migration.sql
- packages/backend/prisma/migrations/20230627062354_drop_scope_from_accounts/migration.sql
- packages/backend/prisma/migrations/20230628045235_use_client_custom_app_creds/migration.sql
- packages/backend/prisma/migrations/20230628061559_create_app_table/migration.sql
- packages/backend/prisma/migrations/20230628150321_link_app_connection/migration.sql
- packages/backend/prisma/migrations/20230629051826_/migration.sql
- packages/backend/prisma/schema.prisma
- packages/backend/prisma/seed.ts
- packages/backend/routes/v1/connection/index.ts
- packages/backend/routes/v1/crm/auth.ts
- packages/backend/routes/v1/metadata.ts
- packages/backend/services/auth.ts
- packages/backend/services/connection.ts
- packages/js/src/index.ts
- packages/js/vite.config.js
- packages/react/src/lib/revert-dev.js
- Allow oauth flow via customer apps (if any), or use revert app
- Granular scope for customer apps
#90 #91
> feat: oauth flow via customer apps and granular permissions

- packages/backend/services/auth.ts
- packages/client/src/home/apiKeys.tsx
- packages/client/src/home/index.tsx
- packages/client/src/home/integrations.tsx
- packages/client/src/home/navbar.tsx
> feat: custom app credentials w/ Revert APIs

- packages/backend/config.ts
- packages/backend/helpers/verifyRevertWebhook.ts
- packages/backend/routes/index.ts
- packages/backend/services/connection.ts
Use webhook `signature` level verification
> feat: add webhook verification via svix

- packages/backend/package.json
- packages/backend/prisma/migrations/20230719095257_1/migration.sql
- packages/backend/prisma/migrations/20230719102118_1/migration.sql
- packages/backend/prisma/schema.prisma
- packages/backend/routes/index.ts
- packages/backend/services/auth.ts
- packages/client/src/home/apiKeys.tsx
- packages/client/src/home/editCredentials.tsx
- packages/client/src/home/integrations.tsx
-   [ ] Tested userflow in `staging` environment
> feat: create default environments

- packages/backend/services/auth.ts
- packages/client/src/home/integrations.tsx
> fix edit ui

- packages/backend/routes/v1/metadata.ts
- packages/backend/services/metadata.ts
- packages/client/src/home/integrations.tsx
> add pipedrive on ui

- packages/client/src/home/environmentSelector.tsx
- packages/client/src/home/index.tsx
- packages/client/src/home/navbar.tsx
> dynamic environments on ui

- packages/backend/package.json
- packages/backend/prisma/scripts/backward.sql
Adds prisma helper scripts 
-   [x] Internal chore
> chore: add manual migrations scripts

- packages/backend/routes/v1/crm/auth.ts
-   [ ] Test A
-   [ ] Test B
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [ ] My changes generate no new warnings
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes
-   [ ] Any dependent changes have been merged and published …
> hotfix: fix webhooks

- packages/backend/services/auth.ts
- Removes unnecessary logs when tokens are refreshed. 
- Adds a granular sentry alert on failure 
-   [x] Internal change
No testing required
> chore: remove log on refresh

- packages/client/src/home/environmentSelector.tsx
> enhancement: update css

- packages/backend/services/auth.ts
> chore: update error message

- packages/backend/routes/index.ts
> fix: build due to naming conflict

- packages/backend/helpers/hubspot.ts
- packages/backend/services/crm/contact.ts
- packages/backend/services/crm/deal.ts
- packages/backend/services/crm/lead.ts
- packages/backend/services/crm/note.ts
> ensure break statements are added

- packages/backend/services/connection.ts
Tightens the prisma query when fetching data. 
Fixes production issue reported on Sentry. 
-   [x] Tested locally
> hotfix: fix prisma query

- README.md
- fern/api/docs/intro.mdx
Tiny documentation update. 
N/A
> chore(docs): minor update

- fern/api/docs/docs.yml
- fern/fern.config.json
1. Adds navigation links to the documentation. 
2. Upgrades Fern
n/a
> chore(docs): add navlinks

- README.md
- packages/backend/routes/index.ts
- scripts/backend/backup_rds.sh
- scripts/backend/backup_table.sh
- Add internal backup scripts for tables & the primary database. 
- Add message from landing page to internal slack alert. 
- Update readme
-   [x] Internal
n/a
> chore: add db backup scripts

- README.md
- packages/backend/README.md
> chore(docs): update readme

- .github/workflows/deploy-js-sdk.yaml
Adds a `gh`action to build the js sdk on push. 
> enhancement: add github action to build js sdk

- .github/workflows/deploy-js-sdk.yaml
chore: update js sdk gh action
> add step to upload to s3 & update cloudfront

- packages/js/src/index.ts
> update js sdk

- packages/backend/prisma/migrations/20230814121503_1/migration.sql
- packages/backend/prisma/schema.prisma
- packages/backend/services/auth.ts
- packages/client/src/home/index.tsx
- packages/client/src/home/navbar.tsx
Adds workspace name on integration dashboard
-   [x] Test locally for new & old accounts
> enhancement: add workspace name on integration dashboard

- packages/backend/index.ts
Fixes the rate limiter error. 
> fix: add trust proxy value on rate limiter

- .github/dependabot.yml
- .gitignore
add dependabot for deps management.
> chore(repo): add dependabot

- packages/backend/config.ts
- packages/backend/helpers/gcmUtil.ts
- packages/backend/prisma/client.ts
- packages/backend/services/connection.ts
- scripts/backend/encrypt_customerEmails.js
AES-256 implemented
Fixes #62
-   [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
> feat: encrypt pii data

- fern/api/docs/mdx/intro.mdx
> :herb: Update CRMs table

- README.md
Updates readme with contributors list.
> chore(docs): add contributors list to readme

- packages/backend/config.ts
- packages/backend/services/auth.ts
add whitelisted domains that can have priority access
> feat: add whitelisted domains that can have priority access

- .github/workflows/deploy-fern-docs.yml
Update required node version for Fern
> chore(docs-gen): update node version

- packages/backend/config.ts
- packages/backend/helpers/gcmUtil.ts
- packages/backend/helpers/tenantIdMiddleware.ts
- packages/backend/package.json
- packages/backend/prisma/client.ts
- packages/backend/prisma/migrations/20230904142724_1/migration.sql
- packages/backend/prisma/schema.prisma
- packages/backend/routes/v1/crm/auth.ts
- packages/backend/services/auth.ts
- packages/backend/services/connection.ts
- yarn.lock
> feat: add connection ids & make encryption work

- README.md
> chore(docs): update integration roadmap, add new CRMs and others

- packages/client/public/index.html
- packages/client/src/routes/index.tsx
update favicon link and add new sign-in route
> chore: update favicon link and add new sign-in route

- LICENSE.txt
> chore(repo): update license

- .prettierignore
- scripts/backend/decrypt_email.js
Add script to use aes-gcm utils outside the backend service
> chore(repo): add a script to use gcm outside service

- packages/backend/helpers/tenantIdMiddleware.ts
- packages/backend/routes/v1/crm/auth.ts
- packages/backend/services/auth.ts
chore: move logs to a single func
> chore: move logs to a single func

- packages/backend/services/metadata.ts
> chore: more verbose logs

- fern/api/definition/common/unified.yml
> chore: refine docs

- fern/api/definition/common/unified.yml
- fern/api/definition/crm/contact.yml
- fern/api/definition/crm/deal.yml
- fern/api/definition/crm/event.yml
- fern/api/definition/crm/lead.yml
- fern/api/definition/crm/note.yml
- fern/api/definition/crm/task.yml
- fern/api/definition/crm/user.yml
update fern ymls with correct description
> chore(docs): update fern ymls with correct description

- packages/backend/services/Internal/account.ts
> improve logs

- packages/backend/Dockerfile
> chore(repo): fix builds

- packages/backend/Dockerfile
> fix build cache attempt

- packages/backend/index.ts
skip health-check logs on morgan
> chore: skip health-check logs

- fern/api/definition/crm/properties.yml
- packages/backend/services/crm/properties.ts
Add custom properties api for pipedrive. 
Fixes #200 
> feat: add custom properties api for pipedrive

- README.md
> chore(repo): update cal link

- .github/FUNDING.yml
update to a direct open collective link
> chore: update to a direct open collective link

- README.md
- fern/api/docs/mdx/how-it-works.mdx
Add architecture overview diagram
> chore(docs): add architecture overview diagram

- packages/client/public/index.html
- packages/client/src/home/apiKeys.tsx
- packages/client/src/home/editCredentials.tsx
- packages/client/src/routes/index.tsx
- Adds analytics with Microsoft clarity on UI. 
- Adds a `catchall` router for UI
-   [x] Testes with MS Clarity
> feat: add analytics on app ui

- .github/workflows/deploy-db-changes.yml
add yarn install on build step
Fixes the issue of yarn not being present on self-hosted runners. 
> fix: add yarn install on build step

- packages/backend/routes/v1/chat/auth.ts
- packages/backend/routes/v1/crm/auth.ts
Add webhook events for slack connections
Closes #211 
-   [x] Tested with Svix 
> feat: add webhooks for slack connections

- packages/react/package.json
- packages/vue/package.json
> chore(repo): bump sdk versions

- CONTRIBUTING.md
Typo in line #16 in ref: `contribution.md`
No dependencies
No break on code
No previous issue related. 
-   [ ] Test A
-   [ ] Test B
There is no test. Just a minor contribution on documentation.
-   [x] I have performed a …
> Typo in documentation

- .env.example
- packages/backend/README.md
- packages/vue/package.json
> chore: update readme

- README.md
> chore(repo): add hacker news badge 

- fern/api/docs/docs.yml
- fern/api/docs/mdx/developer-guides.mdx
> chore(docs): improve local setup

- fern/api/docs/docs.yml
- fern/api/docs/mdx/usecases.mdx
Add use case section to documentation.
> chore(docs): add use case section

- fern/api/docs/docs.yml
- fern/api/docs/mdx/usecases.mdx
> nit: fix typo in docs

- fern/api/docs/docs.yml
- fern/api/docs/mdx/crm-supported.mdx
- fern/api/docs/mdx/how-it-works.mdx
- fern/api/docs/mdx/intro.mdx
- fern/api/docs/mdx/messaging-supported.mdx
- fern/api/docs/mdx/usecases.mdx
update supported APIs and remove crm specific terms
> docs: update supported APIs and remove crm specific terms

- .github/workflows/check-pr-title.yml
add conventional commits check on every PR going forward automatically through a GH Action.
> feat: add conventional commits check

- package.json
- yarn.lock
> chore: upgrade fern dev dependency

- packages/backend/Dockerfile
fix docker build for api with correct fern version
> fix: docker build with correct fern version

- fern/generators.yml
fix: correct fern auto-gen filepath
> fix: correct fern auto-gen filepath

- fern/definition/crm/event.yml
- packages/backend/services/crm/event.ts
Add events delete api endpoint for various CRMs that we support. 
-   [x] Tested E2E with different CRMs
> feat: add event delete api endpoint

- .github/workflows/deploy-db-changes.yml
cleanup self hosted runner directory after job
> fix: cleanup self hosted runner directory after job

- .github/workflows/deploy-db-changes.yml
Upgrade to `actions/checkout@v4` & fix self-hosted runner issue with memory outage.
> fix: upgrade `actions/checkout@v4`

- packages/backend/index.ts
json formatted logs for better analytics
> feat: json formatted logs for better analytics

- packages/backend/services/crm/event.ts
hotfix for allowing event creation on pipedrive
-   [x] Tested locally extensively
> fix: hotfix for allowing event creation on pipedrive

- packages/client/src/home/integrations.tsx
> fix: minor ui alignment fix

- packages/client/src/home/index.tsx
- packages/client/src/home/onboarding.tsx
add onboarding page on integration dashboard
> feat: add onboarding page on dashboard

- .github/workflows/deploy-db-changes.yml
> Revert "feat: shift workflows to warp-ubuntu-latest-arm64-2x"

- .github/workflows/deploy-db-changes.yml
Attempts to fix the broken gh action build step for deploying prisma updates
> fix: gh action for prisma deploy

- .github/workflows/deploy-db-changes.yml
reduce installed bundle size in vm while deploying db changes via prisma
> fix: reduce installed bundle size in vm in `ci`           

- packages/backend/services/auth.ts
> feat: [internal] alert on slack for new users

- README.md
update readme with launch socials
> chore(docs): update readme with launch socials

- README.md
- fern/docs/contents/developer-guides.mdx
Add steps to setup clerk for auth 
> docs: add steps to setup clerk for auth 

- README.md
- packages/react/README.md
docs: highlight cloud version in quickstart
> docs: highlight cloud version in quickstart

- .env.example
- .github/workflows/deploy-docker-to-hub.yml
- docker-compose.yml
feat: deploy images to docker hub via gh action
> feat: deploy images to docker hub via gh action

- .github/workflows/deploy-docker-to-hub.yml
fix: set env variables before build stage
> fix: set env variables before build stage

- .github/workflows/deploy-docker-to-hub.yml
> debug: add debug logs on ci

- .github/workflows/deploy-docker-to-hub.yml
> fix: path on docker build

- docker-compose.yml
- fern/docs.yml
- fern/docs/contents/docker-compose.mdx
Add ability to self host with a different postgres & redis instance
-   [x] Tested by running the same steps with docker locally
> feat: add ability to self host with a different postgres & redis instance

- .github/workflows/deploy-docker-to-hub.yml
- packages/backend/db-seed.Dockerfile
ci: ensure images are rebuilt everytime
> ci: ensure images are rebuilt everytime

- README.md
> chore(repo): add API status badge on repo

- fern/definition/internal/analytics.yml
- packages/backend/helpers/endPointLoggerMiddleWare.ts
- packages/backend/index.ts
- packages/backend/routes/index.ts
- packages/backend/services/Internal/analytics.ts
Implement `internal/analytics` endpoint having following schema as a response.
```javascript
{
totalConnections: 168,
recentConnections: [
{ id: '62878b4e647d7bd25db029a3', time: 'Jan 10, 14:48' },
{ id: '20788b4e647d7bd25db029ax', time: 'Jan 10, 14:48' },
{ id: '62878b4e647d7bd25db029a3', time: 'Jan 10, 14:48' },
{ id: '20788b4e647d7bd25db029ax', time: 'Jan 10, 14:48' },
{ id: '62878b4e647d7bd25db029a3', time: 'Jan 10, 14:48' },
],
recentApiCalls: [
{ method: 'GET', apiName: '/v1/crm/contacts/', status: '200' },
{ method: 'POST', apiName: '/v1/crm/deals/', status: '200' },
{ method: 'POST', apiName: '/v1/crm/deals/', status: '200' },
{ method: 'POST', apiName: '/v1/crm/deals/', status: '200' },
{ method: 'POST', apiName: '/v1/crm/deals/', status: '200' },
],
connectedApps: [
{
appName: …
```
> feat: Implement analytics endpoint

- fern/definition/common/types.yml
- fern/definition/internal/analytics.yml
- packages/backend/helpers/endPointLoggerMiddleWare.ts
- packages/backend/index.ts
- packages/backend/routes/index.ts
- packages/backend/services/Internal/analytics.ts
- packages/client/src/home/analytics.tsx
- packages/client/src/home/index.tsx
- packages/client/src/home/integrations.tsx
Add analytics on UI when managing integrations
-   [x] Tested locally
> feat: analytics on integration dashboard

- packages/client/src/home/analytics.tsx
- packages/client/src/home/environmentSelector.tsx
- packages/client/src/home/index.tsx
The environment selector was broken due to improper handling of states. This PR fixes it. 
-   [x] Tested extensively locally
> fix: ensure environment selector is working

- packages/backend/services/metadata.ts
Add place holder api response for ms teams 
> fix: add ms integration in metadata api response

- packages/backend/constants/common.ts
- packages/backend/routes/v1/ticket/auth.ts
- packages/backend/routes/v1/ticket/index.ts
Trello oauth fixed on defaut revert app.
-   [X] Tested Oauth on default revertPublicToken
> fix: trello auth default credentials loading

- packages/backend/routes/v1/ticket/auth.ts
> fix: add content-type header

- packages/backend/routes/v1/ticket/auth.ts
> add logger

- packages/backend/config.ts
> fix: client credential typo jira

- packages/backend/routes/v1/ticket/index.ts
Trello error handling while fetching token.
-   [X] I have commented my code, particularly in hard-to-understand areas
> fix: trello oauth error handling

- packages/backend/index.ts
Handled response in fall through middleware to prevent server crash
-   [X] Intentionally made invalid requests to check status of server and sentry
-   [X] I have commented my code, particularly in hard-to-understand areas
> fix: Sentry fall through middlware handling

- .github/workflows/deploy-fern-docs.yml
- fern/generators.yml
Add python & node-ts sdks
-   [X] New feature (non-breaking change which adds functionality)
> feat: add python & node-ts sdks

- .github/workflows/deploy-fern-docs.yml
> fix: ensure fern token is present

- fern/docs/contents/quick-start.mdx
Adds documentation changes for backend SDK
> docs: add backend sdk references

- .github/workflows/deploy-fern-docs.yml
> add missing pypi token

- fern/docs.yml
- fern/docs/contents/crm-supported.mdx
- fern/docs/contents/guides/clickup.mdx
- fern/docs/contents/guides/close.mdx
- fern/docs/contents/guides/discord.mdx
- fern/docs/contents/guides/hubspot.mdx
- fern/docs/contents/guides/jira.mdx
- fern/docs/contents/guides/linear.mdx
- fern/docs/contents/guides/pipedrive.mdx
- fern/docs/contents/guides/salesforce.mdx
- fern/docs/contents/guides/slack.mdx
- fern/docs/contents/guides/trello.mdx
- fern/docs/contents/guides/zoho-crm.mdx
- fern/docs/contents/messaging-supported.mdx
- fern/docs/contents/ticketing-supported.mdx
- fern/docs/contents/usecases.mdx
Add integration guides for supported APIs
> docs: add integration guides for supported APIs

- fern/docs/contents/intro.mdx
> docs: fix path relative path for quick start

- fern/docs/contents/docker-compose.mdx
- Minor changes to enhance the doc.
-   [ ] Test A
-   [ ] Test B
-   [ ] My code follows the style guidelines of this …
> docs: update docker-compose.mdx

- fern/docs/contents/developer-guides.mdx
- fern/docs/contents/docker-compose.mdx
- fern/docs/contents/usecases.mdx
Fix dead links on docs.revert.dev
-   [X] I have commented my code, particularly in hard-to-understand areas
> fix: dead links on docs.revert.dev

- packages/client/src/home/analytics.tsx
Handles the case when ui breaks when no analytics data is present for fresh accounts
> fix: handle ui when no analytics data is present

- fern/docs/contents/developer-guides.mdx
docs: updated the doc with the step to install PostgreSQL before seeding the database with sample data
Not applicable. 
> docs: update `developer-guides.mdx` with steps to install PostgreSQL

- fern/docs/contents/developer-guides.mdx
Updates the developer guide with step to sync the database with the schema.
No tests required.
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes
-   [ ] Any dependent changes have been merged and published in downstream modules
> docs: update developer-guides.mdx with step to apply existing migrations

- CONTRIBUTING.md
- fern/docs.yml
- fern/docs/contents/add-integration-guide.mdx
Added guide to build & contribute custom third party integration
Fixes #353
-   [X] This change requires a documentation update
-   [X] I have made corresponding changes to the documentation
> docs: build custom integration guide added

- packages/backend/routes/v1/crm/auth.ts
fetch `org_url` from env if revert_app is false
> fix: fetch org url from env if revert_app is false

- fern/definition/common/unified.yml
fix `associations` in reads
With preview of docs in local
> docs: fix `associations` in reads

- packages/backend/helpers/crm/transform/preprocess.ts
- packages/backend/services/crm/deal.ts
Fields  `isWon` , `probability` , `amount` align consistently with the types mentioned in documentation for hubspot.
-   [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [X] Create and fetch deal with above mentioned fields. Refer there types on revert docs.
> fix: hubspot deal fields

- packages/backend/helpers/tenantAuthMiddleware.ts
Hotfix to ensure field mapping config gets the right config for a tenant
Tested with the duplicate `t_id`s for different accounts
> fix: ensure field mapping config gets the right config

- packages/backend/helpers/tenantAuthMiddleware.ts
- packages/backend/routes/v1/crm/fieldMapping.ts
ensure correct middleware gets used
> fix: ensure correct middleware gets used

- packages/backend/helpers/tenantAuthMiddleware.ts
- packages/js/src/index.ts
get correct t_id config when field mapping is required
> fix: get correct t_id config

- fern/generators.yml
- packages/backend/.gitignore
- packages/backend/oas/openapi.yml
Adds an auto generated open-api spec from fern for developers who would prefer that instead. 
-   [x] Internal
No testing is required for this. 
> chore(dev-ex): add open api spec

- .github/workflows/deploy-fern-docs.yml
- .github/workflows/deploy-js-sdk.yaml
allow manual deploys of gh workflows
> chore: allow manual deploys of gh workflows

- fern/docs/contents/add-integration-guide.mdx
- fern/docs/contents/developer-guides.mdx
- added and rewrote docs for `contribute an api integration`  section in docs for revert.
- added and rewrote docs for `developer guide` section in docs for revert.
> docs: docs improvement for integrating apps and local setup

- packages/client/src/App.css
- packages/client/src/home/environmentSelector.tsx
- packages/client/src/home/index.tsx
- packages/client/src/home/integrations.tsx
- packages/client/src/home/navbar.tsx
- packages/client/src/home/onboarding.tsx
update dashboard ui styling
Cosmetic change only, no tests required. 
> feat: update & enhance dashboard ui

- packages/client/src/home/environmentSelector.tsx
- packages/client/src/home/integrations.tsx
Minor refactor of integration dashboard
> refactor: modularise app configurations on ui

- packages/client/src/home/index.tsx
Add request integration button back
> fix: add request integration button back

- fern/definition/connection.yml
- fern/definition/field-mapping.yml
- packages/backend/oas/openapi.yml
- packages/backend/routes/index.ts
- packages/backend/routes/v1/crm/index.ts
- packages/backend/routes/v1/fieldMapping.ts
- packages/backend/services/connection.ts
- packages/client/src/home/index.tsx
- packages/js/src/index.ts
1. feat: add integration-status api
2. refactor: add endpoints for field-mapping feature
3. fix: fix bug with incorrect tab selection on dashboard
-   [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
Tested the entire OAuth + Field mapping flow
> feat: field mapping api enhancements

- fern/definition/connection.yml
- fern/definition/crm/properties.yml
- packages/backend/oas/openapi.yml
- packages/backend/services/crm/properties.ts
Add `isCustomField` property to crm properties api
Tested with postman
> feat: add `isCustomField` property to crm properties api

- fern/definition/ticket/task.yml
> fix: indendation

- fern/docs.yml
> fix: correct bitbucket guide link

- packages/backend/routes/v1/crm/authHandlers/close.ts
- packages/backend/routes/v1/crm/authHandlers/hubspot.ts
- packages/backend/routes/v1/crm/authHandlers/ms_dynamic_365.ts
- packages/backend/routes/v1/crm/authHandlers/pipedrive.ts
- packages/backend/routes/v1/crm/authHandlers/sfdc.ts
- packages/backend/routes/v1/crm/authHandlers/zoho.ts
- packages/client/src/common/oauth/index.tsx
- packages/client/src/routes/index.tsx
fix: add logs to oauthHandlers
Tested with OAuth flows locally.
> fix: add logs to oauthHandlers

- fern/generators.yml
- package.json
- packages/backend/oas/openapi.yml
> fix: hotfix fern failure

- fern/generators.yml
> fix: add fern config

- packages/backend/package.json
- yarn.lock
> fix: add explicit mime types

- packages/backend/helpers/crm/zoho.ts
feat: add ability to associate contactId with task & event in zohoCRM
Tested thoroughly with postman as well as with real world use-case
> feat: add ability to associate contactId with task & event in zohoCRM

- fern/definition/connection.yml
chore: update import api endpoint docs
NA
> chore: update import api endpoint docs

- fern/docs/contents/crm-supported.mdx
docs: updated ms dynamics support
Just a documentation test
> docs: updated ms dynamics support

- package.json
- packages/js/src/index.ts
Ensure field mappings are saved correctly
Tested by saving mappings for a connection & account
> fix: ensure field mappings are saved correctly

- packages/client/src/features/integration/AddIntegration.tsx
- Fixes, Modal being not overflow to scroll on required screens.  
https://github.com/revertinc/revert/assets/65061890/4fadc24f-27bb-4125-be78-de4f374b3ee1
Fixes & Closes #496 
> fix: App creation Modal to Overflow 

- packages/react/src/lib/useRevertConnect.ts
- Now when ever a config will change it will update within hook, below demo shows the component changes the state and new configs are avialable in hook
https://github.com/revertinc/revert/assets/65061890/e09af35c-0b62-44ea-8ea5-d60b8fa59e64
Closes #564 
> fix: non updation of tenantId in useRevertConnect

- packages/react/package.json
> chore: bump react sdk after upgrade fix

- packages/react/package.json
> chore: bump react sdk version

- packages/react/package.json
chore: bump version of react sdk
> chore: bump react sdk version to `0.0.20`

- packages/backend/helpers/rateLimitMiddleware.ts
Hotfix: rate limiter was not being skipped for certain URLs
Tested extensively 
> fix: rate limiter fix not working

- packages/backend/constants/common.ts
- packages/backend/helpers/auth/processOAuthResult.ts
- packages/backend/redis/client/pubsub.ts
- packages/backend/routes/v1/chat/auth.ts
- packages/backend/routes/v1/chat/authHandlers/discord.ts
- packages/backend/routes/v1/chat/authHandlers/slack.ts
- packages/backend/routes/v1/crm/auth.ts
- packages/backend/routes/v1/crm/authHandlers/close.ts
- packages/backend/routes/v1/crm/authHandlers/hubspot.ts
- packages/backend/routes/v1/crm/authHandlers/ms_dynamic_365.ts
- packages/backend/routes/v1/crm/authHandlers/pipedrive.ts
- packages/backend/routes/v1/crm/authHandlers/sfdc.ts
- packages/backend/routes/v1/crm/authHandlers/zoho.ts
- packages/backend/routes/v1/ticket/auth.ts
- packages/backend/routes/v1/ticket/authHandlers/bitbucket.ts
- packages/backend/routes/v1/ticket/authHandlers/clickup.ts
- packages/backend/routes/v1/ticket/authHandlers/jira.ts
- packages/backend/routes/v1/ticket/authHandlers/linear.ts
- packages/backend/routes/v1/ticket/authHandlers/trello.ts
- packages/backend/routes/v1/ticket/index.ts
- packages/client/package.json
- packages/client/src/common/oauth/index.tsx
- packages/js/src/index.ts
- packages/react/src/App.tsx
- packages/react/src/lib/types/index.ts
- packages/vue/src/lib/types/index.ts
- Closes #572 
- Closes #575 
------------------
> feat: support `redirectUrls` optionally

- packages/react/package.json
- packages/vue/package.json
> chore: bump react & vue sdk versions

- fern/docs.yml
- fern/docs/contents/messaging-supported.mdx
- fern/docs/contents/ticketing-supported.mdx
corrected the link to ticketing system in docs
-   [ ] Test A
-   [ ] Test B
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes
-   [ ] …
> fix: corrected the link to ticketing system in docs

- packages/revert-next/components/ui/dashboard/index.ts
- packages/revert-next/hooks/useConnection.ts
- More useConnection integrations
> fix: add more integrations connection redirects

- packages/revert-next/next.config.mjs
- packages/revert-next/vercel.json
- fixes: 404: NOT_FOUND Code: NOT_FOUND ID:
> fix: vercel 404 not found
